### PR TITLE
Create folder structure and README

### PR DESCRIPTION
**Pull request by fleupold**
Context https://cowservices.slack.com/archives/C036G0J90BU/p1682353087323919

This PR is creating the folder structure for announcement banners in a separate repo. The goal is to make it easier for non technical people to create these banners in times of outages (where technical resources are occupied with technical work).

Once this is merged, I will update https://github.com/cowprotocol/cowswap to use the new repo for announcements. I think other configurations (price estimation strategy) can remain in the main web repo as changes their should be done by technical folks.

### CODE REVIEW

**Review by anxolin — COMMENTED** [review]
Great initiative.

Do you think this repository should be this specific? Are you sure the only possible thing we want to tackle is the banner message? 

In the config branch we have some other things, like using the "legacy pricing" algorithm (that checks on paraswap and other aggregators. 

Some other example. Maybe Marketing wants to change some images (see https://cowservices.slack.com/archives/C03GH01MR09/p1683138750007439)

**Comment by fleupold** [comment]
I don't have strong feelings on what else to add here. Do you have a concrete folder structure in mind you'd want me to adopt? 

The main goal of this repo is to allow anyone in the company to change this message without any technical knowledge (ie no need to have VS Code installed, create a branch or do other slightly involved things). Think about the least technical person on the team being asked in the middle of the night to put a banner, they should be able to do that fast (we will offer some training).

The legacy pricing is something I'd not expect to be part of this repo, but if we want to add other things such as cow fortune content, etc we can for sure add it here (although I'd argue a lot of it is actually better checked into a repo where we want to enforce some level of code review).

I believe it's a bit hard to foresee the use cases, but if you feel strongly I'm happy to rename this repo and move the banners into a subfolder already in anticipation of more use cases.

**Review by alfetopito — APPROVED** [review]
To make it more non-technical-people friendly, would Launch Darkly be a better option?

**Comment by fleupold** [comment]
> To make it more non-technical-people friendly, would Launch Darkly be a better option?

My understanding of the outcome from the slack discussion (linked above) was that we would want to go with github because it's much more cost effective while still allowing per user accounts (and therefore attribution of changes)

**Review by anxolin — APPROVED** [review]
It's fine, let's go with this structure. 

I would hope, at some point not very far we have some easy-to-use, and cheap CMS for this and other content. So I would hope this repository disappears. 

For now is a great patch and buy us some time

**Pull request merged**
